/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Any Shape
 */
export type Schema = Circle | Square;
/**
 * A Circle
 */
export type Circle = Shape & {
  type?: "circle";
  radius?: number;
  [k: string]: unknown;
};
/**
 * A Square
 */
export type Square = Shape & {
  type?: "square";
  radius?: number;
  [k: string]: unknown;
};

/**
 * A Shape
 */
export interface Shape {
  type?: string;
  id?: string;
}
